# Lab 2.1: Introduction to NumPy

**University of Engineering and Technology Peshawar, Nowshera Campus**

**Course:** Machine Learning Lab

**Student Name:** Zohaib Ahmed 
**Registration Number:** 22jzele0481


---

## Table of Contents

1. [Introduction to NumPy](#1-introduction-to-numpy)  
2. [Installation](#2-installation)  
3. [Import NumPy](#3-import-numpy)  
4. [Array Creation](#4-array-creation)  
5. [Indexing and Slicing](#5-indexing-and-slicing)  
6. [Mathematical Operations](#6-mathematical-operations)  
7. [Statistical Functions](#7-statistical-functions)  

---

## 1. Introduction to NumPy

NumPy is a powerful Python library for numerical computing, providing support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays efficiently. It serves as the foundation for many scientific and mathematical Python libraries due to its speed and versatility. NumPy offers capabilities for array manipulation, mathematical operations, linear algebra, random number generation, and more, making it an essential tool for data manipulation and analysis in fields such as machine learning, data science, and engineering. With its efficient implementation in C, NumPy facilitates fast computations and enables seamless integration with other Python libraries and tools. Its simplicity and performance make it a cornerstone of the Python scientific computing ecosystem.

## 2. Installation

We can easily install this library using the terminal. Follow the steps given below to install Numpy:<br>
Step 1: Go to the Windows PowerShell.<br>
Step 2: We can install Numpy with the help of pip easily. Head over to the directory where you want to install the numpy and fire the below command:<br>
__pip install numpy__<br>
__OR__<br>
__conda install numpy__<br>
This is very simple to install.

## 3. Import NumPy

In [1]:
import numpy as np

## 4. Array Creation

### 4.1 Creating an array from list

In [2]:
mylist=[1,3,5,6]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 3, 5, 6])

In [5]:
type(mylist)

list

In [6]:
arr=np.array(mylist)

In [7]:
arr

array([1, 3, 5, 6])

### 4.2 Creating matrix

In [8]:
mylist=[[1,3,5],[4,5,6],[1,4,76],[1,3,5]]

In [9]:
np.array(mylist)

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

In [10]:
mymatrix = np.array(mylist)

In [11]:
mymatrix.shape

(4, 3)

### 4.3 Creating the numpy array by using range function

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### 4.4 Creating the numpy array of only Zeros

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### 4.5 Creating the matrix of only Zeros

In [15]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### 4.6 Creating the matrix of only 1

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.ones((5,5)) +5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [18]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [19]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

### 4.7 Creating of array by using linspace function

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
len(np.linspace(0,10,20))

20

### 4.8 Eye function

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4.9 Random numbers

In [23]:
np.random.rand(5)

array([0.89333566, 0.78275045, 0.92785012, 0.72243668, 0.22283737])

In [24]:
np.random.rand(3,5)

array([[0.19332909, 0.74474162, 0.13922855, 0.23541902, 0.48209067],
       [0.31988261, 0.39782429, 0.94870962, 0.39183639, 0.61317836],
       [0.58819138, 0.78965153, 0.14311801, 0.49968173, 0.87396862]])

In [25]:
np.random.randint(1,100,5)

array([69, 57, 57, 19,  8])

## 5. Indexing and Slicing

In [26]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[8]

8

In [28]:
arr[2]

2

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[:5]

array([0, 1, 2, 3, 4])

In [33]:
arr[4:7]

array([4, 5, 6])

In [34]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

## 6. Mathematical Operations

In [35]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [36]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [37]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## 7. Statistical Functions

In [38]:
arr = np.array([4, 9, 2, 7, 5])
print("Array:", arr)
print("Mean:", arr.mean())
print("Max:", arr.max())
print("Min:", arr.min())
print("Argmax:", arr.argmax())
print("Argmin:", arr.argmin())
print("Standard Deviation:", arr.std())
print("Variance:", arr.var())
print("Median:", np.median(arr))
print("Sum:", arr.sum())
print("Cumulative Sum:", arr.cumsum())
print("Sorted Array:", np.sort(arr))

Array: [4 9 2 7 5]
Mean: 5.4
Max: 9
Min: 2
Argmax: 1
Argmin: 2
Standard Deviation: 2.4166091947189146
Variance: 5.84
Median: 5.0
Sum: 27
Cumulative Sum: [ 4 13 15 22 27]
Sorted Array: [2 4 5 7 9]
